# Generated by Django 2.0.4 on 2018-04-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
    ]
